name: Run Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0
      - run: |
          make test

  test-node:
    strategy:
      matrix:
        version: [18, 19, 20, 21]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}
      - run: |
          make build-npm
          deno run --allow-net mock_server.ts &
          sleep 5 && node node_test.js

  test-cli:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.41.0
      - env:
          LOCKDB_SERVICE_ID: 'reports'
          LOCKDB_API_KEY: 'api-key'
          LOCKDB_SERVER_URL: 'http://127.0.0.1:5678'
        run: |
          deno install --config=deno.json --import-map=import_map.json --allow-net --allow-env=LOCKDB_SERVICE_ID,LOCKDB_API_KEY,LOCKDB_SERVER_URL main.ts --name lockdb
          deno run --allow-net mock_server.ts &
          sleep 5 && ./bash_test.sh 
